# -*- coding: utf-8 -*-
"""problema2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HUbTbmSE1kdqUmXvXxreVq0Qirp9Dcy1
"""

#Problema 2  / 9 ptos x4 pruebas / 36 puntos
#Concatenación de listas o tuplas
#---------------------------------------------------------------------------------
#Confeccione un programa que lea varios elementos y los entregue de manera inversa
#---------------------------------------------------------------------------------
#Ejemplo de entrada:
#         20 90 hola jiji 77
#La salida debe ser
#         (77, 'jiji', 'hola', 90, 20)
t3 = tuple(input().split())
tuplafinal = tuple()
for palabra in t3:
    try:
        numero = int(palabra)
        tuplafinal += (numero,)
    except ValueError:
        tuplafinal += (palabra,)

print(tuplafinal[::-1])